language: node_js
node_js:
  - "9"

cache:
  directories:
    - node_modules
    - packages/inab-native/node_modules
    - packages/inab-shared/node_modules
    - packages/inab-web/node_modules

script:
  - cd packages/inab-shared
  - yarn test
  - yarn build
  - yarn build:flow

  - cd ../inab-web
  - yarn build

  - yarn start&
  - yarn wait-on http://localhost:3000
  - yarn run test:e2e
